- name: Compile LaTeX (pLaTeX + dvipdfmx)
  uses: xu-cheng/latex-action@v3
  with:
    root_file: Bell_Inequality_report.tex
    args: -pdfdvi -interaction=nonstopmode -file-line-error -halt-on-error
